use psy_common::{FileId, Arena};
use psy_vm::dpn::ops::context_trait::{ContextFelt, DPNContext};
use psy_ast::*;
use psy_lexer::Token;

grammar<'input, F, C>(
    file_content: &'input str,
    file_id: FileId,
    module_name: Identifier,
    expr_nodes: &mut Arena<ExprId, ExprNode<F>>,
    stmt_nodes: &mut Arena<StmtId, StmtNode>,
    def_nodes: &mut Arena<DefId, DefinitionNode>,
    interner: &mut Interner,
    _visibility_: Visibility,
    ctx: &mut C
) where F: ContextFelt + From<u32>, C: DPNContext<F>;

use super::{Loc, UserError, LalrpopError};
use std::convert::TryFrom;

ModuleItem: ModuleItemNode = {
    InlineModule => ModuleItemNode::InlineModule(<>),
    ModuleDecl => ModuleItemNode::ModuleDecl(<>),
    Definition => ModuleItemNode::Definition(def_nodes.alloc_item(<>)),
}

Comment: Comment = {
    <l:@L> <line:LineComment> <r:@R> => Comment::new_line(line.to_string(), Location::new(file_id, l, r)),
    <l:@L> <block:BlockComment> <r:@R> => Comment::new_block(block.to_string(), Location::new(file_id, l, r)),
}

pub Module: ModuleNode = {
    <l:@L> <module_items: ModuleItem*>  <r:@R> <back_comments:Comment*> => ModuleNode::new(
        module_name,
        file_id,
        _visibility_,
        module_items,
        def_nodes,
        back_comments,
        Location::new(file_id, l, r),
    )
}

InlineModule: ModuleNode = {
    <l:@L> <comments: Comment*> <visibility:Visibility> MOD <name:Identifier> "{" <module_items: ModuleItem*> <back_comments:Comment*> "}" <r:@R> => ModuleNode::new(
        name,
        file_id,
        visibility,
        module_items,
        def_nodes,
        comments.into_iter().chain(back_comments.into_iter()).collect(),
        Location::new(file_id, l, r),
    )
}

ModuleDecl: (Identifier, Visibility, Location) = {
    <l:@L> <visibility:Visibility> MOD <name:Identifier> ";" <r:@R> => {
        (name, visibility, Location::new(file_id, l, r))
    },
}

Statement: StmtNode = {
    VariableStatement,
    AssignmentStatement,
    ReturnStatement,
    WhileStatement,
    ForStatement,
    Definition => StmtNode::Definition(def_nodes.alloc_item(<>)),
    IntrinsicStatement,
    ExpressionStatement
}

ExpressionStatement: StmtNode = {
    <l:@L> <comments: Comment*> <expr:Expression> ";" <r:@R> => StmtNode::Expression(expr_nodes.alloc_item(expr)),
}

IntrinsicStatement: StmtNode = {
    <l:@L> <comments: Comment*> <variable:ASSERT> "(" <left: Expression> "," <message: STRING?> ","? ")" ";" <r:@R> => {
        StmtNode::Intrinsic(
            IntrinsicStmtNode::Assert {
                left: expr_nodes.alloc_item(left),
                message: message.map(|m| m.to_string()),
                comments,
                location: Location::new(file_id, l, r),
            }
        )
    },
    <l:@L> <comments: Comment*> <variable:ASSERT_EQ> "(" <left: Expression> "," <right: Expression> "," <message: STRING?> ","? ")" ";" <r:@R> => {
        StmtNode::Intrinsic(
            IntrinsicStmtNode::AssertEq {
                left: expr_nodes.alloc_item(left),
                right: expr_nodes.alloc_item(right),
                message: message.map(|m| m.to_string()),
                comments,
                location: Location::new(file_id, l, r),
            }
        )
    },
    <l:@L> <comments: Comment*> <variable:CTX_CLEAR_ENTIRE_TREE> "(" ")" ";" <r:@R> => {
        StmtNode::Intrinsic(
            IntrinsicStmtNode::ClearEntireTree {
                comments,
                location: Location::new(file_id, l, r),
            }
        )
    },
}

Definition: DefinitionNode = {
    ImplDef => DefinitionNode::Impl(<>),
    TraitImplDef => DefinitionNode::TraitImpl(<>),
    TraitDef => DefinitionNode::Trait(<>),
    EnumDef => DefinitionNode::Enum(<>),
    StructDef => DefinitionNode::Struct(<>),
    TypeAliasDef => <>,
    <f:FunctionDef> =>? {
        if f.as_function().unwrap().body.is_none() {
            return Err(LalrpopError::User { error: UserError::FunctionBodyMissing });

        }
        if f.as_function().unwrap().parameters.iter().any(|p|{
             p.name == IdentId::SELF || (p.ty.is_basic() && p.ty.as_basic().unwrap().id == IdentId::TYPE_SELF)
        }) {
            return Err(LalrpopError::User { error: UserError::InvalidSelfParameter });
        }
        Ok(f)
    },
    ConstDef => <>,
    UseDef => DefinitionNode::Use(<>),
}

UseDef: UseNode = {
    <l:@L> <comments: Comment*> <visibility:Visibility> USE <path:UseNode> ";" <r:@R> => {
        UseNode {
            visibility,
            kind: path.0,
            target: path.2,
            segments: path.1,
            comments,
            location: Location::new(file_id, l, r),
        }
    }
}

ImplDef: ImplNode = {
   <l:@L> <comments: Comment*> IMPL <generic_parameters_lhs:GenericParameters> <ty:PathTy> "{" <associated_types:AssociatedTypeValue*> <body:FunctionDef*> <back_comments: Comment*> "}" <r:@R> =>? Ok({
        ImplNode {
            generic_parameters: generic_parameters_lhs,
            ty,
            associated_types: associated_types.into_iter().collect(),
            body: {
                if body.iter().any(|f| {
                     f.as_function().unwrap().body.is_none()
                }) {
                    return Err(LalrpopError::User {
                        error: UserError::FunctionBodyMissing
                    });
                }
                if body.iter().any(|f| {
                    f.as_function()
                        .unwrap()
                        .parameters
                        .iter()
                        .enumerate()
                        .any(|(i, p)| p.name == IdentId::SELF && i != 0)
                }) {
                    return Err(LalrpopError::User {
                        error: UserError::InvalidSelfParameter
                    });
                }
                def_nodes.alloc_items(body)
            },
            comments: comments.into_iter().chain(back_comments.into_iter()).collect(),
            location: Location::new(file_id, l, r),
            is_generated: false,
        }
   })
}

TraitImplDef: TraitImplNode = {
   <l:@L> <comments: Comment*> IMPL <generic_parameters_lhs:GenericParameters> <trait_ty:PathTy> FOR <ty:PathTy> "{" <associated_types:AssociatedTypeValue*> <body:FunctionDef*> <back_comments: Comment*> "}" <r:@R> =>? Ok({
        TraitImplNode {
            generic_parameters: generic_parameters_lhs,
            associated_types: associated_types.into_iter().collect(),
            trait_ty: trait_ty,
            ty,
            body: {
                if body.iter().any(|f| {
                    f.as_function().unwrap().body.is_none()
                }) {
                    return  Err(LalrpopError::User {
                        error: UserError::FunctionBodyMissing
                    });
                }
                if body.iter().any(|f| {
                    f.as_function()
                        .unwrap()
                        .parameters
                        .iter()
                        .enumerate()
                        .any(|(i, p)| p.name == IdentId::SELF && i != 0)
                }) {
                    return Err(LalrpopError::User {
                        error: UserError::InvalidSelfParameter
                    });
                }
                def_nodes.alloc_items(body)
            },
            comments: comments.into_iter().chain(back_comments.into_iter()).collect(),
            location: Location::new(file_id, l, r),
            is_generated: false,
        }
   })
}

AssociatedTypeValue: (Identifier, AssociatedTypeValue) = {
    <l:@L> <comments: Comment*> <visibility: Visibility> TYPE <name:Identifier> "=" <ty:PathTy> ";" <r:@R> =>  (
        name,
        AssociatedTypeValue {
            ty,
            comments,
            visibility,
            location: Location::new(file_id, l, r)
        }
    ),
}

TraitDef: TraitNode = {
   <l:@L> <comments: Comment*> <visibility:Visibility> TRAIT <name:Identifier> <generic_parameters:GenericParameters> "{" <associated_types:TraitAssociatedType*> <body:FunctionDef*> <back_comments: Comment*> "}" <r:@R> => {
       TraitNode {
           generic_parameters,
           associated_types: associated_types.into_iter().collect(),
           name,
           body: def_nodes.alloc_items(body),
           visibility,
           comments: comments.into_iter().chain(back_comments.into_iter()).collect(),
           location: Location::new(file_id, l, r),
       }
   }
}

TraitAssociatedType: (Identifier, AssociatedType) = {
    <l:@L> <comments: Comment*> <visibility:Visibility> TYPE <ty:GenericParameter> ";" <r:@R> => (
        Identifier::new(ty.name, ty.location),
        AssociatedType {constraints: ty.constraints, visibility, location: Location::new(file_id, l, r), comments,}
    )
}

EnumDef: EnumNode = {
    <l:@L> <comments: Comment*> <visibility:Visibility> ENUM <name:Identifier> <generic_parameters:GenericParameters> "{" <variants:Comma<EnumVariant>> "}" <r:@R> => EnumNode {
        name,
        generic_parameters,
        variants,
        visibility,
        comments,
        location: Location::new(file_id, l, r),
    }
}

TypeAliasDef: DefinitionNode = {
    <l:@L> <comments: Comment*> <visibility:Visibility> TYPE <name:Identifier> "=" <ty:PathTy> ";" <r:@R> => DefinitionNode::TypeAlias(TypeAliasNode {
        name,
        ty,
        visibility,
        comments,
        location: Location::new(file_id, l, r),
    })
}

StructDef: StructNode = {
    <l:@L> <comments: Comment*> <attrs:Attribute*> <visibility: Visibility> STRUCT <name:Identifier> <generic_parameters:GenericParameters> "{" <fields:Comma<FieldTypeAnnotation>> "}" <r:@R> => StructNode {
        name,
        generic_parameters,
        fields: fields.into_iter().collect(),
        attrs,
        visibility,
        comments,
        location: Location::new(file_id, l, r),
        is_generated: false
    }
}

ConstDef: DefinitionNode = {
    <l:@L> <comments: Comment*> <visibility:Visibility> CONST <name:Identifier> ":" <ty:ConstType> "=" <value:Expression> ";" <r:@R> => DefinitionNode::Const(ConstNode {
        name,
        ty,
        value: expr_nodes.alloc_item(value),
        visibility,
        comments,
        location: Location::new(file_id, l, r),
    })
}

FunctionDef: DefinitionNode = {
    <l:@L> <comments: Comment*> <attrs:Attribute*> <visibility:Visibility> <qualifier:Qualifier> FN <name:IdentifierOrNew> <generic_parameters:GenericParameters> "(" <parameters:Comma<FunctionParameter>> ")" <return_type:FunctionReturn?> <block_expr:BlockExpression> <r:@R> =>? Ok(DefinitionNode::Function(FunctionNode {
        name,
        parameters,
        generic_parameters,
        body: Some(expr_nodes.alloc_item(block_expr)),
        return_type,
        qualifier,
        visibility,
        attrs,
        comments,
        location: Location::new(file_id, l, r),
    })),
    <l:@L> <comments: Comment*> <attrs:Attribute*> <visibility:Visibility> <qualifier:Qualifier> FN <name:IdentifierOrNew> <generic_parameters:GenericParameters> "(" <parameters:Comma<FunctionParameter>> ")" <return_type:FunctionReturn?> ";" <r:@R> =>? Ok(DefinitionNode::Function(FunctionNode {
        name,
        parameters,
        generic_parameters,
        body: None,
        return_type,
        qualifier,
        visibility,
        attrs,
        comments,
        location: Location::new(file_id, l, r),
    }))
}

Attribute: AttrNode = {
    <l:@L> "#" "[" <name:AttributePath>  <properties:AttributeProperties> "]" <r:@R> => {
        let mut path = name;
        let name = path.pop().expect("attribute path has at least one segment");
        AttrNode { path, name, properties, location: Location::new(file_id, l, r) }
    }
}

AttributePath: Vec<Identifier> = {
    <head:Identifier> <tail:("::" <Identifier>)*> => {
        let mut path = vec![head];
        path.extend(tail);
        path
    }
}

AttributeProperties: Vec<Identifier> = {
    <l:@L> "(" <properties:Comma<Identifier>> ")" <r:@R> => properties,
    () => vec![]
}

Qualifier: Qualifier = {
    <l:@L> <is_const:CONST?> <is_extern:EXTERN?> <r:@R> => Qualifier {
        is_extern: is_extern.is_some(),
        is_const: is_const.is_some(),
        location: Location::new(file_id, l, r),
    },
}

TypeQualifier: TypeQualifier = {
    <l:@L> <is_mutable: MUT?> <r:@R> => TypeQualifier {
        is_mutable: is_mutable.is_some(),
        location: Location::new(file_id, l, r),
    },
}

FunctionSignature: UncheckedType = {
    <l:@L> FN "(" <parameters:Comma<PathTy>> ")" <return_type:FunctionReturn?> <r:@R> => UncheckedType::FunctionSignature(
        Box::new(FunctionSignature {parameters, return_type}),
        Location::new(file_id, l, r)
    )
}

FunctionParameter: FunctionParameter = {
    <l:@L> <type_qualifier: TypeQualifier> <name:IdentifierOrSelf> ":" <ty:PathTy> <r:@R> => FunctionParameter::new(name, type_qualifier, ty, Location::new(file_id, l, r)),
    <l:@L> <type_qualifier: TypeQualifier> <name:SELF> <r:@R> => {
        FunctionParameter::new(
            Identifier::new(IdentId::SELF, Location::new(file_id, l, r)),
            type_qualifier,
            UncheckedType::Basic(Identifier::new(IdentId::TYPE_SELF, Location::new(file_id, l, r))),
            Location::new(file_id, l, r)
        )
    },
}

FunctionReturn: UncheckedType = {
    <l:@L> "->" <ty:PathTy> <r:@R> => ty,
}

EnumVariant: EnumVariant = {
    <l:@L> <name:Identifier> <r:@R> => EnumVariant::Basic(name),
    <l:@L> <name:Identifier> "(" <members:Comma<PathTy>> ")" <r:@R> => EnumVariant::Tuple(name, members),
    <l:@L> <name:Identifier> "{" <fields:Comma<FieldTypeAnnotation>> "}" <r:@R> => EnumVariant::Struct(
        name,
        fields.into_iter().map(|(field_name, field_type)| (field_name, field_type)).collect()
    )
}

TypeAnnotation: (Identifier, UncheckedType) = {
    <l:@L> <name:Identifier> ":" <ty:PathTy> <r:@R> => (name, ty),
    <l:@L> <name:Identifier> <r:@R> => (name, UncheckedType::Unknown)
}

FieldTypeAnnotation: (Identifier, StructField)  = {
    <l:@L> <comments: Comment*> <attrs:Attribute*> <visibility:Visibility> <name:Identifier> ":" <ty:PathTy> <r:@R> => (
        name,
        StructField { ty, attrs, visibility, comments, location: Location::new(file_id, l, r) }
    ),
}

Visibility: Visibility = {
    PUB => Visibility::Public,
    () => Visibility::Private
}

GenericParameters: Vec<GenericParameter> = {
    <l:@L> "<" <generic_parameters:Comma<GenericParameter>> ">" <r:@R> => generic_parameters,
    () => vec![]
}

GenericParameter: GenericParameter = {
    <l:@L> <name:Identifier> <constraints: GenericConstraints> <r:@R> => GenericParameter::new(
        name.id,
        constraints,
        Location::new(file_id, l, r)
    )
}

GenericConstraints: Vec<UncheckedType> = {
    <l:@L> ":" <constraints:Plus<PathTy>> <r:@R> => constraints,
    () => vec![]
}

BlockExpression: ExprNode<F> = {
    <l:@L> "{" <stmts:Statement*> <comments: Comment*> <ret:Expression?> "}" <r:@R> => {
        ExprNode::BlockExpr(
            BlockExprNode {
                stmts: stmt_nodes.alloc_items(stmts),
                expr: ret.map(|x| expr_nodes.alloc_item(x)),
                expr_comments: comments,
                location: Location::new(file_id, l, r),
            }
        )
    }
}

WhileStatement: StmtNode = {
    <l:@L> <comments: Comment*> WHILE <predicate:Expression> <block_expr:BlockExpression> <r:@R>  => StmtNode::While(WhileNode {
        predicate: expr_nodes.alloc_item(predicate),
        body: expr_nodes.alloc_item(block_expr),
        comments,
        location: Location::new(file_id, l, r),
    }),
}

MatchExpression: ExprNode<F> = {
    <l:@L> MATCH <scrutinee:Expression> "{" <arms:Comma<MatchArm>> "}" <r:@R> => ExprNode::Match(MatchNode {
        scrutinee: expr_nodes.alloc_item(scrutinee),
        arms,
        location: Location::new(file_id, l, r),
    }),
}

MatchArm: MatchArm = {
    <l:@L> <pattern:MatchPattern> "=>" <expr:Expression> <r:@R> => MatchArm {
        pattern,
        body: expr_nodes.alloc_item(expr),
        location: Location::new(file_id, l, r),
    }
}

MatchPattern: MatchPattern = {
    <l:@L> <pattern:Expression> <r:@R> => MatchPattern::Value(expr_nodes.alloc_item(pattern), Location::new(file_id, l, r)),
    <l:@L>  "_" <r:@R> =>  MatchPattern::PlaceHolder(Location::new(file_id, l, r)),

}

ForStatement: StmtNode = {
    <l:@L> <comments: Comment*> FOR <variable:Identifier> IN <start:Expression> ".." <end:Expression> <block_expr:BlockExpression> <r:@R> => StmtNode::For(
        ForNode {
            variable,
            start: expr_nodes.alloc_item(start),
            end: expr_nodes.alloc_item(end),
            body: expr_nodes.alloc_item(block_expr),
            comments,
            location: Location::new(file_id, l, r),
        }
    ),
}

IfExpression: ExprNode<F> = {
    <l:@L> <if_branch:IfBranch> <elseif_branches:ElseIfBranch*> <else_branch:ElseBranch?> <r:@R> => ExprNode::IfExpr(
        IfExprNode {
            if_branch,
            elseif_branches,
            else_branch,
            location: Location::new(file_id, l, r),
        }
    ),
}

IfBranch: Case = {
    <l:@L> IF <predicate:Expression> <block_expr:BlockExpression> <r:@R> => Case::new(
        expr_nodes.alloc_item(predicate),
        expr_nodes.alloc_item(block_expr),
        Location::new(file_id, l, r)
    ),
}

ElseIfBranch: Case = {
    <l:@L> ELSE IF <predicate:Expression> <block_expr:BlockExpression> <r:@R> => Case::new(
        expr_nodes.alloc_item(predicate),
        expr_nodes.alloc_item(block_expr),
        Location::new(file_id, l, r)
    ),
}

ElseBranch: ExprId = {
    <l:@L> ELSE <block_expr:BlockExpression> <r:@R> => expr_nodes.alloc_item(block_expr),
}

ReturnStatement: StmtNode = {
    <l:@L> <comments: Comment*> RETURN <ret:Expression?> ";" <r:@R> => StmtNode::Return(ReturnNode{
        expr_id: ret.map(|x| expr_nodes.alloc_item(x)),
        comments,
        location: Location::new(file_id, l, r),
    })
}

TupleType: UncheckedType = {
    <l:@L> "(" <types:Comma<PathTy>> ")" <r:@R> => UncheckedType::Tuple(types, Location::new(file_id, l, r))
}

TupleExpression: ExprNode<F> = {
    <l:@L> "(" <first:Expression> "," <rest:Comma<Expression>> ")" <r:@R> => {
        let mut elements = vec![expr_nodes.alloc_item(first)];
        elements.extend(rest.into_iter().map(|e| expr_nodes.alloc_item(e)));
        ExprNode::<F>::Tuple(TupleExprNode { elements, location: Location::new(file_id, l, r) })
    },
    //if the tuple has only one element, it should be treated as a normal expression
    "(" <expr:Expression> ")" => ExprNode::<F>::Parentheses(expr_nodes.alloc_item(expr)),
}

VariableStatement: StmtNode = {
    <l:@L> <comments: Comment*> LET <type_qualifier: TypeQualifier> <decl:TypeAnnotation> "=" <value:Expression> ";" <r:@R> => StmtNode::Variable(
        VariableNode {
            name: decl.0,
            ty: decl.1,
            qualifier: type_qualifier,
            value: expr_nodes.alloc_item(value),
            comments,
            location: Location::new(file_id, l, r),
        }
    ),
}

AssignmentStatement: StmtNode = {
    <l:@L> <comments: Comment*> <variable:Expression> "=" <value:Expression> ";" <r:@R> => StmtNode::Assignment(
        AssignmentNode::new(expr_nodes.alloc_item(variable), AssignmentOperator::Eq, expr_nodes.alloc_item(value), comments, Location::new(file_id, l, r))
    ),
    <l:@L> <comments: Comment*> <variable:Expression> "+=" <value:Expression> ";" <r:@R> => StmtNode::Assignment(
        AssignmentNode::new(expr_nodes.alloc_item(variable), AssignmentOperator::AddAssign, expr_nodes.alloc_item(value), comments, Location::new(file_id, l, r))
    ),
    <l:@L> <comments: Comment*>  <variable:Expression> "-=" <value:Expression> ";" <r:@R> => StmtNode::Assignment(
        AssignmentNode::new(expr_nodes.alloc_item(variable), AssignmentOperator::SubAssign, expr_nodes.alloc_item(value), comments, Location::new(file_id, l, r))
    ),
    <l:@L> <comments: Comment*> <variable:Expression> "*=" <value:Expression> ";" <r:@R> => StmtNode::Assignment(
        AssignmentNode::new(expr_nodes.alloc_item(variable), AssignmentOperator::MulAssign, expr_nodes.alloc_item(value), comments, Location::new(file_id, l, r))
    ),
    <l:@L> <comments: Comment*> <variable:Expression> "/=" <value:Expression> ";" <r:@R> => StmtNode::Assignment(
        AssignmentNode::new(expr_nodes.alloc_item(variable), AssignmentOperator::DivAssign, expr_nodes.alloc_item(value), comments, Location::new(file_id, l, r))
    ),
    <l:@L> <comments: Comment*> <variable:Expression> "%=" <value:Expression> ";" <r:@R> => StmtNode::Assignment(
        AssignmentNode::new(expr_nodes.alloc_item(variable), AssignmentOperator::ModAssign, expr_nodes.alloc_item(value), comments, Location::new(file_id, l, r))
    ),
    <l:@L> <comments: Comment*> <variable:Expression> "&=" <value:Expression> ";" <r:@R> => StmtNode::Assignment(
        AssignmentNode::new(expr_nodes.alloc_item(variable), AssignmentOperator::BitAndAssign, expr_nodes.alloc_item(value), comments, Location::new(file_id, l, r))
    ),
    <l:@L> <comments: Comment*> <variable:Expression> "|=" <value:Expression> ";" <r:@R> => StmtNode::Assignment(
        AssignmentNode::new(expr_nodes.alloc_item(variable), AssignmentOperator::BitOrAssign, expr_nodes.alloc_item(value), comments, Location::new(file_id, l, r))
    ),
    <l:@L> <comments: Comment*> <variable:Expression> "^=" <value:Expression> ";" <r:@R> => StmtNode::Assignment(
        AssignmentNode::new(expr_nodes.alloc_item(variable), AssignmentOperator::BitXorAssign, expr_nodes.alloc_item(value), comments, Location::new(file_id, l, r))
    ),
    <l:@L> <comments: Comment*> <variable:Expression> "<<=" <value:Expression> ";" <r:@R> => StmtNode::Assignment(
        AssignmentNode::new(expr_nodes.alloc_item(variable), AssignmentOperator::BitShlAssign, expr_nodes.alloc_item(value), comments, Location::new(file_id, l, r))
    ),
    <l:@L> <comments: Comment*> <variable:Expression> ">>=" <value:Expression> ";" <r:@R> => StmtNode::Assignment(
        AssignmentNode::new(expr_nodes.alloc_item(variable), AssignmentOperator::BitShrAssign, expr_nodes.alloc_item(value), comments, Location::new(file_id, l, r))
    )
}


Expression: ExprNode<F> = {
    #[precedence(level="1")]
    Term,
    #[precedence(level="2")]
    IntrinsicExpression,
    <l:@L> <callee:Expression> <generic_parameters:Monomorphization> "(" <args:ArgumentList> ")" <r:@R> => {
       if let ExprNode::<F>::MemberAccess(MemberAccessNode {
          target: receiver, ..
       }) = &callee {
            ExprNode::<F>::MemberCall(
               MemberCallNode {
                   receiver: receiver.clone(),
                   callee: expr_nodes.alloc_item(callee),
                   generic_parameters,
                   args: expr_nodes.alloc_items(args),
                   location: Location::new(file_id, l, r),
               }
            )
       } else {
            ExprNode::<F>::Call(
               CallNode {
                   callee: expr_nodes.alloc_item(callee),
                   generic_parameters,
                   args: expr_nodes.alloc_items(args),
                   location: Location::new(file_id, l, r),
               }
            )
       }
    },
    <l:@L> <variable:Expression> "[" <index:Expression> "]" <r:@R> => ExprNode::<F>::IndexAccess(IndexAccessNode {
        target: expr_nodes.alloc_item(variable),
        index: expr_nodes.alloc_item(index),
        location: Location::new(file_id, l, r),
    }),
    <l:@L> <variable:Expression> "." <index:U64> <r:@R> => ExprNode::<F>::TupleAccess(TupleAccessNode {
        target: expr_nodes.alloc_item(variable),
        index: index as usize,
        location: Location::new(file_id, l, r),
    }),
    <l:@L> <variable:Expression> "." <field:Identifier> <r:@R> => ExprNode::<F>::MemberAccess(MemberAccessNode {
        target: expr_nodes.alloc_item(variable),
        field,
        location: Location::new(file_id, l, r),
    }),
    <l:@L> <lhs:Expression> AS <ty:ConstType> <r:@R> => ExprNode::<F>::Cast(
        CastNode::new(expr_nodes.alloc_item(lhs), ty, Location::new(file_id, l, r))
    ),

    #[precedence(level="4")] #[assoc(side="right")]
    <l:@L> "!" <rhs:Expression> <r:@R> => ExprNode::<F>::Unary(
        UnaryNode{operator: UnaryOperator::Not, rhs: expr_nodes.alloc_item(rhs), location: Location::new(file_id, l, r)}
    ),
    #[precedence(level="4")] #[assoc(side="right")]
    <l:@L> "-" <rhs:Expression> <r:@R> => ExprNode::<F>::Unary(
        UnaryNode{operator: UnaryOperator::Neg, rhs: expr_nodes.alloc_item(rhs), location: Location::new(file_id, l, r)}
    ),

    #[precedence(level="6")] #[assoc(side="left")]
    <l:@L> <lhs:Expression> "**" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::Pow, expr_nodes.alloc_item(rhs), Location::new(file_id, l, r))
    ),
    <l:@L> <lhs:Expression> "*" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::Mul, expr_nodes.alloc_item(rhs), Location::new(file_id, l, r))
    ),
    <l:@L> <lhs:Expression> "/" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::Div, expr_nodes.alloc_item(rhs), Location::new(file_id, l, r))
    ),
    <l:@L> <lhs:Expression> "%" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::Mod, expr_nodes.alloc_item(rhs), Location::new(file_id, l, r))
    ),

    #[precedence(level="7")] #[assoc(side="left")]
    <l:@L> <lhs:Expression> "+" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::Add, expr_nodes.alloc_item(rhs), Location::new(file_id, l, r))
    ),
    <l:@L> <lhs:Expression> "-" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::Sub, expr_nodes.alloc_item(rhs), Location::new(file_id, l, r))
    ),

    #[precedence(level="8")] #[assoc(side="left")]
    <l:@L> <lhs:Expression> "<<" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::BitShl, expr_nodes.alloc_item(rhs), Location::new(file_id, l, r))
    ),
    <l:@L> <lhs:Expression> ">>" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::BitShr, expr_nodes.alloc_item(rhs), Location::new(file_id, l, r))
    ),

    #[precedence(level="9")] #[assoc(side="left")]
    <l:@L> <lhs:Expression> "&" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::BitAnd, expr_nodes.alloc_item(rhs), Location::new(file_id, l, r))
    ),

    #[precedence(level="10")] #[assoc(side="left")]
    <l:@L> <lhs:Expression> "^" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::BitXor, expr_nodes.alloc_item(rhs), Location::new(file_id, l, r))
    ),

    #[precedence(level="11")] #[assoc(side="left")]
    <l:@L> <lhs:Expression> "|" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::BitOr, expr_nodes.alloc_item(rhs), Location::new(file_id, l, r))
    ),

    #[precedence(level="12")] #[assoc(side="left")]
    <l:@L> <lhs:Expression> ">" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::Gt, expr_nodes.alloc_item(rhs), Location::new(file_id, l, r))
    ),
    <l:@L> <lhs:Expression> "<" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::Lt, expr_nodes.alloc_item(rhs), Location::new(file_id, l, r))
    ),
    <l:@L> <lhs:Expression> ">=" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::Gte, expr_nodes.alloc_item(rhs), Location::new(file_id, l, r))
    ),
    <l:@L> <lhs:Expression> "<=" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::Lte, expr_nodes.alloc_item(rhs), Location::new(file_id, l, r))
    ),

    #[precedence(level="13")] #[assoc(side="left")]
    <l:@L> <lhs:Expression> "==" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::Eq, expr_nodes.alloc_item(rhs), Location::new(file_id, l, r))
    ),
    <l:@L> <lhs:Expression> "!=" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::Neq, expr_nodes.alloc_item(rhs), Location::new(file_id, l, r))
    ),

    #[precedence(level="14")] #[assoc(side="left")]
    <l:@L> <lhs:Expression> "&&" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::And, expr_nodes.alloc_item(rhs), Location::new(file_id, l, r))
    ),

    #[precedence(level="15")] #[assoc(side="left")]
    <l:@L> <lhs:Expression> "||" <rhs:Expression> <r:@R> => ExprNode::<F>::Binary(
        BinaryNode::new(expr_nodes.alloc_item(lhs), BinaryOperator::Or, expr_nodes.alloc_item(rhs), Location::new(file_id, l, r))
    ),

    #[precedence(level="16")]
    LambdaFunctionExpression
}

Term: ExprNode<F> = {
    ValueExpression,
    PathExpression,
    IfExpression,
    MatchExpression,
    BlockExpression
}

IntrinsicExpression: ExprNode<F> = {
    <l:@L> <variable:MEM_TRANSMUTE> "#" "<" <target_type:PathTy> ">" "(" <data: Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::MemTransmute {
                data: expr_nodes.alloc_item(data),
                target_type,
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:MEM_SIZE_OF> "#" "<" <query_type:PathTy> ">" "(" ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::MemSizeOf {
                query_type,
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:STORAGE_READ_RANGE> "(" <contract_state_tree_height: Expression> "," <user_id: Expression> "," <contract_id: Expression> "," <offset: Expression> "," <length: Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::StorageReadRange {
                contract_state_tree_height: expr_nodes.alloc_item(contract_state_tree_height),
                user_id: expr_nodes.alloc_item(user_id),
                contract_id: expr_nodes.alloc_item(contract_id),
                offset: expr_nodes.alloc_item(offset),
                length: expr_nodes.alloc_item(length),
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:STORAGE_WRITE_RANGE> "(" <offset: Expression> "," <values: Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::StorageWriteRange {
                offset: expr_nodes.alloc_item(offset),
                values: expr_nodes.alloc_item(values),
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:STORAGE_READ> "(" <contract_state_tree_height: Expression> "," <user_id: Expression> "," <contract_id: Expression> "," <offset: Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::StorageRead {
                contract_state_tree_height: expr_nodes.alloc_item(contract_state_tree_height),
                user_id: expr_nodes.alloc_item(user_id),
                contract_id: expr_nodes.alloc_item(contract_id),
                offset: expr_nodes.alloc_item(offset),
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:STORAGE_WRITE> "(" <offset: Expression> "," <value: Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::StorageWrite {
                offset: expr_nodes.alloc_item(offset),
                value: expr_nodes.alloc_item(value),
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:Hash> "(" <data:Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::Hash {
                data: expr_nodes.alloc_item(data),
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:Keccak256> "(" <data:Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::Keccak256 {
                data: expr_nodes.alloc_item(data),
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:HashTwoToOne> "(" <left:Expression> "," <right:Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::HashTwoToOne {
                left: expr_nodes.alloc_item(left),
                right: expr_nodes.alloc_item(right),
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:CTX_GET_USER_ID> "(" ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::GetUserId {
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:CTX_GET_CONTRACT_ID> "(" ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::GetContractId {
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:CTX_GET_CONTRACT_DEPLOYER> "(" <contract_id:Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::GetContractDeployer {
                contract_id: expr_nodes.alloc_item(contract_id),
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:CTX_GET_CALLER_CONTRACT_ID> "(" ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::GetCallerContractId {
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:CTX_GET_CHECKPOINT_ID> "(" ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::GetCheckpointId {
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:CTX_GET_CHECKPOINT_STATS> "(" <checkpoint_id:Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::GetCheckpointStats {
                checkpoint_id: expr_nodes.alloc_item(checkpoint_id),
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:CTX_GET_REGISTER_USERS_ROOT> "(" <checkpoint_id:Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::GetRegisterUsersRoot {
                checkpoint_id: expr_nodes.alloc_item(checkpoint_id),
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:CTX_GET_GUTAS_ROOT> "(" <checkpoint_id:Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::GetGutasRoot {
                checkpoint_id: expr_nodes.alloc_item(checkpoint_id),
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:CTX_GET_CHECKPOINT_USER_TREE_ROOT> "(" <checkpoint_id:Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::GetCheckpointUserTreeRoot {
                checkpoint_id: expr_nodes.alloc_item(checkpoint_id),
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:CTX_GET_CHECKPOINT_CONTRACT_TREE_ROOT> "(" <checkpoint_id:Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::GetCheckpointContractTreeRoot {
                checkpoint_id: expr_nodes.alloc_item(checkpoint_id),
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:CTX_GET_CHECKPOINT_DEPOSIT_TREE_ROOT> "(" <checkpoint_id:Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::GetCheckpointDepositTreeRoot {
                checkpoint_id: expr_nodes.alloc_item(checkpoint_id),
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:CTX_GET_CHECKPOINT_WITHDRAWAL_TREE_ROOT> "(" <checkpoint_id:Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::GetCheckpointWithdrawalTreeRoot {
                checkpoint_id: expr_nodes.alloc_item(checkpoint_id),
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:CTX_GET_CHECKPOINT_USER_REGISTRATION_TREE_ROOT> "(" <checkpoint_id:Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::GetCheckpointUserRegistrationTreeRoot {
                checkpoint_id: expr_nodes.alloc_item(checkpoint_id),
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:CTX_GET_DEPLOY_CONTRACTS_ROOT> "(" <checkpoint_id:Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::GetDeployContractsRoot {
                checkpoint_id: expr_nodes.alloc_item(checkpoint_id),
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:CTX_GET_GUTA_FEES_COLLECTED> "(" <checkpoint_id:Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::GetGutaFeesCollected {
                checkpoint_id: expr_nodes.alloc_item(checkpoint_id),
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:CTX_GET_DA_FEES_COLLECTED> "(" <checkpoint_id:Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::GetDaFeesCollected {
                checkpoint_id: expr_nodes.alloc_item(checkpoint_id),
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:CTX_GET_USER_OPS_PROCESSED> "(" <checkpoint_id:Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::GetUserOpsProcessed {
                checkpoint_id: expr_nodes.alloc_item(checkpoint_id),
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:CTX_GET_TOTAL_TRANSACTIONS> "(" <checkpoint_id:Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::GetTotalTransactions {
                checkpoint_id: expr_nodes.alloc_item(checkpoint_id),
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:CTX_GET_SLOTS_MODIFIED> "(" <checkpoint_id:Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::GetSlotsModified {
                checkpoint_id: expr_nodes.alloc_item(checkpoint_id),
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:CTX_GET_DEPLOY_CONTRACTS_COMPLETED> "(" <checkpoint_id:Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::GetDeployContractsCompleted {
                checkpoint_id: expr_nodes.alloc_item(checkpoint_id),
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:CTX_GET_REGISTER_USERS_COMPLETED> "(" <checkpoint_id:Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::GetRegisterUsersCompleted {
                checkpoint_id: expr_nodes.alloc_item(checkpoint_id),
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:CTX_GET_GUTAS_COMPLETED> "(" <checkpoint_id:Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::GetGutasCompleted {
                checkpoint_id: expr_nodes.alloc_item(checkpoint_id),
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:CTX_GET_LAST_NONCE> "(" ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::GetLastNonce {
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:CTX_GET_USER_PUBLIC_KEY_HASH> "(" ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::GetUserPublicKeyHash {
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:CTX_GET_SESSION_PROOF_TREE_ROOT> "(" ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::GetSessionProofTreeRoot {
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:CTX_GET_STATE_HASH_AT> "(" <slot_index: Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::GetStateHashAt {
                slot_index: expr_nodes.alloc_item(slot_index),
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:IMT_GET> "(" <key: Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::ImtGet {
                key: expr_nodes.alloc_item(key),
                base_offset: expr_nodes.alloc_item(ExprNode::Value(ValueNode::Felt(F::from(0), Location::new(file_id, l, r)))),
                capacity: expr_nodes.alloc_item(ExprNode::Value(ValueNode::Felt(F::from(0), Location::new(file_id, l, r)))),
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:IMT_GET> "(" <key: Expression> "," <base_offset: Expression> "," <capacity: Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::ImtGet {
                key: expr_nodes.alloc_item(key),
                base_offset: expr_nodes.alloc_item(base_offset),
                capacity: expr_nodes.alloc_item(capacity),
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:IMT_GET_OTHER_USER> "("
        <contract_state_tree_height: Expression> ","
        <user_id: Expression> ","
        <contract_id: Expression> ","
        <key: Expression> ","
        <base_offset: Expression> ","
        <capacity: Expression>
    ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::ImtGetOtherUser {
                contract_state_tree_height: expr_nodes.alloc_item(contract_state_tree_height),
                user_id: expr_nodes.alloc_item(user_id),
                contract_id: expr_nodes.alloc_item(contract_id),
                key: expr_nodes.alloc_item(key),
                base_offset: expr_nodes.alloc_item(base_offset),
                capacity: expr_nodes.alloc_item(capacity),
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:IMT_CONTAINS_OTHER_USER> "("
        <contract_state_tree_height: Expression> ","
        <user_id: Expression> ","
        <contract_id: Expression> ","
        <key: Expression> ","
        <base_offset: Expression> ","
        <capacity: Expression>
    ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::ImtContainsOtherUser {
                contract_state_tree_height: expr_nodes.alloc_item(contract_state_tree_height),
                user_id: expr_nodes.alloc_item(user_id),
                contract_id: expr_nodes.alloc_item(contract_id),
                key: expr_nodes.alloc_item(key),
                base_offset: expr_nodes.alloc_item(base_offset),
                capacity: expr_nodes.alloc_item(capacity),
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:CTX_GET_OTHER_CONTRACT_STATE_HASH_AT> "(" <contract_state_tree_height: Expression> "," <contract_id: Expression> "," <slot_index: Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::GetOtherContractStateHashAt {
                contract_state_tree_height: expr_nodes.alloc_item(contract_state_tree_height),
                contract_id: expr_nodes.alloc_item(contract_id),
                slot_index: expr_nodes.alloc_item(slot_index),
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:CTX_GET_OTHER_USER_CONTRACT_STATE_HASH_AT> "(" <contract_state_tree_height: Expression> "," <user_id: Expression> "," <contract_id: Expression> "," <slot_index: Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::GetOtherUserContractStateHashAt {
                contract_state_tree_height: expr_nodes.alloc_item(contract_state_tree_height),
                user_id: expr_nodes.alloc_item(user_id),
                contract_id: expr_nodes.alloc_item(contract_id),
                slot_index: expr_nodes.alloc_item(slot_index),
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:CTX_SET_STATE_HASH_AT> "(" <slot_index: Expression> "," <new_value: Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::CSetStateHashAt {
                slot_index: expr_nodes.alloc_item(slot_index),
                new_value: expr_nodes.alloc_item(new_value),
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:IMT_SET> "(" <key: Expression> "," <new_value: Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::ImtSet {
                key: expr_nodes.alloc_item(key),
                new_value: expr_nodes.alloc_item(new_value),
                base_offset: expr_nodes.alloc_item(ExprNode::Value(ValueNode::Felt(F::from(0), Location::new(file_id, l, r)))),
                capacity: expr_nodes.alloc_item(ExprNode::Value(ValueNode::Felt(F::from(0), Location::new(file_id, l, r)))),
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:IMT_SET> "(" <key: Expression> "," <new_value: Expression> "," <base_offset: Expression> "," <capacity: Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::ImtSet {
                key: expr_nodes.alloc_item(key),
                new_value: expr_nodes.alloc_item(new_value),
                base_offset: expr_nodes.alloc_item(base_offset),
                capacity: expr_nodes.alloc_item(capacity),
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:IMT_CONTAINS> "(" <key: Expression> "," <base_offset: Expression> "," <capacity: Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::ImtContains {
                key: expr_nodes.alloc_item(key),
                base_offset: expr_nodes.alloc_item(base_offset),
                capacity: expr_nodes.alloc_item(capacity),
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:INVOKE_SYNC> "#" "<" <return_type:Ty> ">"  "(" <contract_id: Expression> "," <method_id: Expression>  "," <inputs: Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::InvokeSync {
                contract_id: expr_nodes.alloc_item(contract_id),
                method_id: expr_nodes.alloc_item(method_id),
                inputs: expr_nodes.alloc_item(inputs),
                return_type,
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:INVOKE_DEFERRED> "(" <contract_id: Expression> "," <method_id: Expression>  "," <inputs: Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::InvokeDeferred {
                contract_id: expr_nodes.alloc_item(contract_id),
                method_id: expr_nodes.alloc_item(method_id),
                inputs: expr_nodes.alloc_item(inputs),
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:SUM_BITS> "(" <bits: Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::SumBits {
                bits: expr_nodes.alloc_item(bits),
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:SPLIT_BITS> "(" <target: Expression> "," <num_bits: U64> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::SplitBits {
                target: expr_nodes.alloc_item(target),
                num_bits: num_bits,
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:EMIT> "(" <event_data: Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::Emit {
                event_data: expr_nodes.alloc_item(event_data),
                location: Location::new(file_id, l, r)
            }
        )
    },
    <l:@L> <variable:CHECK_SECP_SIGN> "(" <pub_key: Expression> "," <msg: Expression>  "," <sig: Expression> ")" <r:@R> => {
        ExprNode::Intrinsic(
            IntrinsicExprNode::Secp256k1Verify {
                pub_key: expr_nodes.alloc_item(pub_key),
                msg: expr_nodes.alloc_item(msg),
                sig: expr_nodes.alloc_item(sig),
                location: Location::new(file_id, l, r)
            }
        )
    }
}

ValueExpression: ExprNode<F> = {
    FeltExpression,
    BoolExpression,
    U32Expression,
    ArrayExpression,
    TupleExpression,
    NEW <StructExpression>
}

FeltExpression: ExprNode<F> = {
    <l:@L> <n:U64> <r:@R> => ExprNode::<F>::Value(ValueNode::Felt(ctx.op_const(n), Location::new(file_id, l, r))),
}

BoolExpression: ExprNode<F> = {
    <l:@L> <b:BOOL> <r:@R> => ExprNode::<F>::Value(ValueNode::Bool(if b { ctx.op_true() } else { ctx.op_false() }, Location::new(file_id, l, r)))
}

U32Expression: ExprNode<F> = {
    <l:@L> <n:U32> <r:@R> => {
        ExprNode::<F>::Value(ValueNode::U32(ctx.op_const_u32(n), Location::new(file_id, l, r)))
    },
}

StructExpression: ExprNode<F> = {
   <l:@L> <name:PathTy> "{" <kv:Comma<KeyValue>> "}" <r:@R> => {
        let name = ExprNode::Path(PathNode::from_target_ty(name));
        ExprNode::<F>::Value(
            ValueNode::Struct(
                expr_nodes.alloc_item(name),
                vec![],
                kv.into_iter().collect(),
                Location::new(file_id, l, r),
            )
        )
    }
}

KeyValue: (Identifier, ExprId) = {
    <l:@L> <name:Identifier> ":" <value:Expression> <r:@R> => (name, expr_nodes.alloc_item(value)),
    <l:@L> <name:Identifier> <r:@R> => (name, expr_nodes.alloc_item(ExprNode::Path(PathNode::from_target(UncheckedType::Basic(name)))))
}

LambdaFunctionExpression: ExprNode<F> = {
    <l:@L> "||" <return_type:FunctionReturn?> <block_expr:BlockExpression> <r:@R> => ExprNode::<F>::LambdaFunction(
        LambdaFunctionNode {
            parameters: vec![],
            body: expr_nodes.alloc_item(block_expr),
            return_type,
            location: Location::new(file_id, l, r),
        }
    ),
    <l:@L> "|" <parameters:Comma<FunctionParameter>> "|" <return_type:FunctionReturn?> <block_expr:BlockExpression> <r:@R> => ExprNode::<F>::LambdaFunction(
        LambdaFunctionNode {
            parameters,
            body: expr_nodes.alloc_item(block_expr),
            return_type,
            location: Location::new(file_id, l, r),
        }
    )
}

PathExpression: ExprNode<F> = {
    <l:@L> <segments: (<BasicIdentOrGenericTy> "::")*> <target: BasicIdentTy> <r:@R> => {
        let segs = segments.into_iter().map(|seg| seg).collect::<Vec<_>>();
        let root = if segs.is_empty() {
            None
        } else {
            Some(segs.first().unwrap().clone())
        };
        let segments = segs.into_iter().skip(1).collect::<Vec<_>>();
        ExprNode::Path(PathNode {
            root,
            segments,
            target,
            is_ty: false,
            location: Location::new(file_id, l, r),
        })
    },
    <l:@L> <segments: (<BasicIdentOrGenericTy> "::")+> <target: NEW> <r:@R> => {
        let segs = segments.into_iter().map(|seg| seg).collect::<Vec<_>>();
        let root = if segs.is_empty() {
            None
        } else {
            Some(segs.first().unwrap().clone())
        };
        let segments = segs.into_iter().skip(1).collect::<Vec<_>>();
        ExprNode::Path(PathNode {
            root,
            segments,
            target: UncheckedType::Basic(Identifier::new(IdentId::NEW, Location::new(file_id, l, r))),
            is_ty: false,
            location: Location::new(file_id, l, r),
        })
    },
}

PathTy: UncheckedType = {
    <l:@L> <segments: (<BasicIdentTy> "::")*> <target:Ty> <r:@R> => {
        let segs = segments.into_iter().map(|seg| seg).collect::<Vec<_>>();
        if segs.is_empty() {
            target
        } else {
            UncheckedType::Path(Box::new(PathNode {
                root: Some(segs.first().unwrap().clone()),
                segments: segs.into_iter().skip(1).collect::<Vec<_>>(),
                target,
                is_ty: true,
                location: Location::new(file_id, l, r),
            }))
        }
    },
}

ArgumentList: Vec<ExprNode<F>> = {
    <items:Sep<Expression, ",">> => items
}

ArrayExpression: ExprNode<F> = {
    <l:@L> "[" <elements:Comma<Expression>> "]" <r:@R> => ExprNode::<F>::Value(
        ValueNode::Array(u32::try_from(elements.len()).unwrap(), expr_nodes.alloc_items(elements), Location::new(file_id, l, r)),
    ),
    <l:@L> "[" <element:Expression> ";" <n:U64> "]" <r:@R> => ExprNode::<F>::Value({
        let size = u32::try_from(n).unwrap();
        let mut elements = Vec::with_capacity(size as usize);
        for _ in 0..size {
            elements.push(expr_nodes.alloc_item(element.clone()));
        }
        ValueNode::Array(size, elements, Location::new(file_id, l, r))
    }),
}

UseNode: (Identifier, Vec<Identifier>, Option<Identifier>) =
    <a:ModuleUseKind> "::" <h:(<Identifier> "::")*> <t:IdentifierOrAll> => {
        (a, h, t)
    };

Monomorphization: Vec<UncheckedType> = {
    <l:@L> "#" "<" <generic_parameters:Comma<MonomorphizationTy>> ">" <r:@R> => generic_parameters,
    () => vec![]
}

MonomorphizationTy: UncheckedType = {
    ConstValue,
    PathTy
}

ConstValue: UncheckedType = {
    <l:@L> <n:U64> <r:@R> => UncheckedType::Const(ConstValue::Felt(n), Location::new(file_id, l, r)),
    <l:@L> <n:BOOL> <r:@R> => UncheckedType::Const(ConstValue::Bool(n), Location::new(file_id, l, r)),
    <l:@L> <n:U32> <r:@R> => UncheckedType::Const(ConstValue::U32(n), Location::new(file_id, l, r)),
}

Ty: UncheckedType = {
    BasicType,
    ArrayType,
    TupleType,
    GenericType,
    FunctionSignature
}

GenericType: UncheckedType = {
    <l:@L> <name:Identifier> "<" <generic_parameters:Comma<MonomorphizationTy>> ">" <r:@R> => UncheckedType::Generic(name, generic_parameters, Location::new(file_id, l, r)),
    <l:@L>  "[" <ty:PathTy> ";" <n:Identifier> "]" <r:@R> => UncheckedType::Generic(
        Identifier::new(IdentId::TYPE_ARRAY, Location::new(file_id, l, r)),
        vec![ty, UncheckedType::Basic(n)],
        Location::new(file_id, l, r)
    )
}

ArrayType: UncheckedType = {
    <l:@L> "[" <ty:PathTy> ";" <n:U64> "]" <r:@R> => UncheckedType::Array(Box::new(ty), u32::try_from(n).unwrap(), Location::new(file_id, l, r))
}

ConstType: UncheckedType = {
    <l:@L> <ty:TYPE_FELT>  <r:@R> => UncheckedType::Basic(Identifier::new(IdentId::TYPE_FELT, Location::new(file_id, l, r))),
    <l:@L> <ty:TYPE_BOOL>  <r:@R> => UncheckedType::Basic(Identifier::new(IdentId::TYPE_BOOL, Location::new(file_id, l, r))),
    <l:@L> <ty:TYPE_U32>   <r:@R> => UncheckedType::Basic(Identifier::new(IdentId::TYPE_U32, Location::new(file_id, l, r))),
}

BasicType: UncheckedType = {
    ConstType,
    <l:@L> <ty:TYPE_SELF>  <r:@R> => UncheckedType::Basic(Identifier::new(IdentId::TYPE_SELF, Location::new(file_id, l, r))),
    <l:@L> <ty:Identifier> <r:@R> => UncheckedType::Basic(ty)
}

ModuleUseKind: Identifier = {
    <l:@L> SELF            <r:@R> => Identifier::new(IdentId::SELF, Location::new(file_id, l, r)),
    <l:@L> SUPER           <r:@R> => Identifier::new(IdentId::SUPER, Location::new(file_id, l, r)),
    <l:@L> CRATE           <r:@R> => Identifier::new(IdentId::CRATE, Location::new(file_id, l, r)),
    <l:@L>  <k:Identifier> <r:@R> => k
}

IdentifierOrAll: Option<Identifier> = {
    Identifier => Some(<>),
    <l:@L> "*" <r:@R> => None
}

IdentifierOrSelf: Identifier = {
    Identifier,
    <l:@L> <name:SELF> <r:@R> => Identifier::new(IdentId::SELF, Location::new(file_id, l, r)),
}

IdentifierOrNew: Identifier = {
    Identifier,
    <l:@L> <name:NEW> <r:@R> => Identifier::new(IdentId::NEW, Location::new(file_id, l, r))
}

BasicIdentTy: UncheckedType = {
    BasicType,
    <l:@L> <ty:SELF> <r:@R> => UncheckedType::Basic(Identifier::new(IdentId::SELF, Location::new(file_id, l, r)))
}

BasicIdentOrGenericTy: UncheckedType = {
    BasicIdentTy,
    <l:@L> "<" <ty:GenericType> ">" <r:@R> => ty,
    <l:@L> "<" <ty:ArrayType> ">" <r:@R> => ty,
    <l:@L> "<" <ty:PathTy> AS <trait_ty:PathTy> ">" <r:@R> => UncheckedType::TraitCast(Box::new(ty), Box::new(trait_ty), Location::new(file_id, l, r)),
}

Identifier: Identifier = {
    <l:@L> <name:IDENT> <r:@R> => Identifier::new(interner.intern_ident(name), Location::new(file_id, l, r))
}

Sep<E,S>: Vec<E> =
    <v0:(<E> S)*> <e1:E?> =>
        v0.into_iter().chain(e1).collect();

DoubleColon<E>: Vec<E> = Sep<E, "::">;
Dot<E>: Vec<E> = Sep<E, ".">;
Comma<E>: Vec<E> = Sep<E, ",">;
Plus<E>: Vec<E> = Sep<E, "+">;

extern {
    type Location = Loc;
    type Error = UserError;

    enum Token<'input> {
        CONST => Token::KeywordConst,
        LET => Token::KeywordLet,

        MUT => Token::KeywordMut,

        FN => Token::KeywordFn,
        STRUCT => Token::KeywordStruct,
        ENUM => Token::KeywordEnum,
        IMPL => Token::KeywordImpl,
        TRAIT => Token::KeywordTrait,
        RETURN => Token::KeywordReturn,
        MATCH => Token::KeywordMatch,
        IF => Token::KeywordIf,
        ELSE => Token::KeywordElse,
        WHILE => Token::KeywordWhile,
        FOR => Token::KeywordFor,
        IN => Token::KeywordIn,
        WHERE => Token::KeywordWhere,

        ASSERT => Token::IntrinsicAssert,
        ASSERT_EQ => Token::IntrinsicAssertEq,
        Hash => Token::IntrinsicHash,
        Keccak256 => Token::IntrinsicKeccak256,
        HashTwoToOne => Token::IntrinsicHashTwoToOne,
        MEM_TRANSMUTE => Token::IntrinsicMemTransmute,
        MEM_SIZE_OF => Token::IntrinsicMemSizeOf,
        STORAGE_READ => Token::IntrinsicStorageRead,
        STORAGE_WRITE => Token::IntrinsicStorageWrite,
        STORAGE_READ_RANGE => Token::IntrinsicStorageReadRange,
        STORAGE_WRITE_RANGE => Token::IntrinsicStorageWriteRange,
        CTX_GET_USER_ID => Token::IntrinsicCtxGetUserId,
        CTX_GET_CONTRACT_ID => Token::IntrinsicCtxGetContractId,
        CTX_GET_CONTRACT_DEPLOYER => Token::IntrinsicCtxGetContractDeployer,
        CTX_GET_CALLER_CONTRACT_ID => Token::IntrinsicCtxGetCallerContractId,
        CTX_GET_CHECKPOINT_ID => Token::IntrinsicCtxGetCheckpointId,
        CTX_GET_CHECKPOINT_STATS => Token::IntrinsicCtxGetCheckpointStats,
        CTX_GET_REGISTER_USERS_ROOT => Token::IntrinsicCtxGetRegisterUsersRoot,
        CTX_GET_GUTAS_ROOT => Token::IntrinsicCtxGetGutasRoot,
        CTX_GET_CHECKPOINT_USER_TREE_ROOT => Token::IntrinsicCtxGetCheckpointUserTreeRoot,
        CTX_GET_CHECKPOINT_CONTRACT_TREE_ROOT => Token::IntrinsicCtxGetCheckpointContractTreeRoot,
        CTX_GET_CHECKPOINT_DEPOSIT_TREE_ROOT => Token::IntrinsicCtxGetCheckpointDepositTreeRoot,
        CTX_GET_CHECKPOINT_WITHDRAWAL_TREE_ROOT => Token::IntrinsicCtxGetCheckpointWithdrawalTreeRoot,
        CTX_GET_CHECKPOINT_USER_REGISTRATION_TREE_ROOT => Token::IntrinsicCtxGetCheckpointUserRegistrationTreeRoot,
        CTX_GET_DEPLOY_CONTRACTS_ROOT => Token::IntrinsicCtxGetDeployContractsRoot,
        CTX_GET_GUTA_FEES_COLLECTED => Token::IntrinsicCtxGetGutaFeesCollected,
        CTX_GET_DA_FEES_COLLECTED => Token::IntrinsicCtxGetDAFeesCollected,
        CTX_GET_USER_OPS_PROCESSED => Token::IntrinsicCtxGetUserOpsProcessed,
        CTX_GET_TOTAL_TRANSACTIONS => Token::IntrinsicCtxGetTotalTransactions,
        CTX_GET_SLOTS_MODIFIED => Token::IntrinsicCtxGetSlotsModified,
        CTX_GET_DEPLOY_CONTRACTS_COMPLETED => Token::IntrinsicCtxGetDeployContractsCompleted,
        CTX_GET_REGISTER_USERS_COMPLETED => Token::IntrinsicCtxGetRegisterUsersCompleted,
        CTX_GET_GUTAS_COMPLETED => Token::IntrinsicCtxGetGutasCompleted,
        CTX_CLEAR_ENTIRE_TREE => Token::IntrinsicCtxClearEntireTree,
        CTX_GET_LAST_NONCE => Token::IntrinsicCtxGetLastNonce,
        CTX_GET_USER_PUBLIC_KEY_HASH => Token::IntrinsicCtxGetUserPublicKeyHash,
        CTX_GET_SESSION_PROOF_TREE_ROOT => Token::IntrinsicCtxGetSessionProofTreeRoot,
        CTX_GET_STATE_HASH_AT => Token::IntrinsicCtxGetStateHashAt,
        CTX_GET_OTHER_CONTRACT_STATE_HASH_AT => Token::IntrinsicCtxGetOtherContractStateHashAt,
        CTX_GET_OTHER_USER_CONTRACT_STATE_HASH_AT => Token::IntrinsicCtxGetOtherUserContractStateHashAt,
        CTX_SET_STATE_HASH_AT => Token::IntrinsicCtxSetStateHashAt,
        IMT_GET => Token::IntrinsicImtGet,
        IMT_GET_OTHER_USER => Token::IntrinsicImtGetOtherUser,
        IMT_CONTAINS_OTHER_USER => Token::IntrinsicImtContainsOtherUser,
        IMT_SET => Token::IntrinsicImtSet,
        IMT_CONTAINS => Token::IntrinsicImtContains,

        INVOKE_SYNC => Token::IntrinsicInvokeSync,
        INVOKE_DEFERRED => Token::IntrinsicInvokeDeferred,

        CHECK_SECP_SIGN => Token::IntrinsicSecp256k1Verify,

        SUM_BITS => Token::IntrinsicSumBits,
        SPLIT_BITS => Token::IntrinsicSplitBits,

        EMIT => Token::IntrinsicEmit,

        MOD => Token::KeywordMod,
        USE => Token::KeywordUse,
        SUPER => Token::KeywordSuper,
        CRATE => Token::KeywordCrate,
        SELF => Token::KeywordSelf,

        PUB => Token::KeywordPub,

        IDENT => Token::Ident(<&'input str>),

        BOOL => Token::Bool(<bool>),
        U64 => Token::U64(<u64>),
        U32 => Token::U32(<u32>),
        STRING => Token::String(<&'input str>),

        TYPE_BOOL => Token::TypeBool,
        TYPE_FELT => Token::TypeFelt,
        TYPE_U32 => Token::TypeU32,
        TYPE_ARRAY => Token::TypeArray,
        TYPE_SELF => Token::TypeSelf,

        AS => Token::KeywordAs,
        TYPE => Token::KeywordType,

        EXTERN => Token::KeywordExtern,
        NEW => Token::KeywordNew,

        "#" => Token::Pound,
        "_" => Token::Placeholder,

        "(" => Token::LParen,
        ")" => Token::RParen,
        "{" => Token::LBrace,
        "}" => Token::RBrace,
        "[" => Token::LBracket,
        "]" => Token::RBracket,

        "=" => Token::Assign,
        ";" => Token::Semicolon,
        "," => Token::Comma,
        "." => Token::Dot,
        ".." => Token::DoubleDot,
        ":" => Token::Colon,
        "::" => Token::DoubleColon,
        "->" => Token::Arrow,
        "=>" => Token::FatArrow,

        "+" => Token::OperatorAdd,
        "-" => Token::OperatorSub,
        "*" => Token::OperatorMul,
        "/" => Token::OperatorDiv,
        "**" => Token::OperatorPow,
        "%" => Token::OperatorMod,

        "==" => Token::OperatorEq,
        "!=" => Token::OperatorNeq,
        "<" => Token::OperatorLt,
        "<=" => Token::OperatorLte,
        ">" => Token::OperatorGt,
        ">=" => Token::OperatorGte,
        "&&" => Token::OperatorAnd,
        "||" => Token::OperatorOr,

        "&" => Token::OperatorBitAnd,
        "|" => Token::OperatorBitOr,
        "^" => Token::OperatorBitXor,

        "<<" => Token::OperatorShl,
        ">>" => Token::OperatorShr,

        "!" => Token::OperatorNot,

        "+=" => Token::OperatorAddAssign,
        "-=" => Token::OperatorSubAssign,
        "*=" => Token::OperatorMulAssign,
        "/=" => Token::OperatorDivAssign,
        "%=" => Token::OperatorModAssign,

        "|=" => Token::OperatorBitOrAssign,
        "&=" => Token::OperatorBitAndAssign,
        "^=" => Token::OperatorBitXorAssign,

        "<<=" => Token::OperatorBitShlAssign,
        ">>=" => Token::OperatorBitShrAssign,

        LineComment => Token::LineComment(<&'input str>),
        BlockComment => Token::BlockComment(<&'input str>),
    }
}
